<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-G08ULK8" name="Command line test" tests="5" failures="2" timestamp="19 Aug 2024 14:48:35 GMT" time="3.844" errors="0">
  <testcase name="insertPerson_TEST" time="0.317" classname="com.testng.testAPI"/>
  <testcase name="insertPerson_parametros_TEST" time="0.118" classname="com.testng.testAPI"/>
  <testcase name="insertPerson_parametros_TEST" time="0.092" classname="com.testng.testAPI"/>
  <testcase name="lista_persona_TEST" time="0.215" classname="com.testng.testAPI">
    <failure type="java.lang.AssertionError" message="expected [21] but found [24]">
      <![CDATA[java.lang.AssertionError: expected [21] but found [24]
	at com.testng.testAPI.lista_persona_TEST(testAPI.java:116)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- lista_persona_TEST -->
  <testcase name="timeTestOne" time="0.53" classname="com.testng.testAPI">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.timeTestOne() didn&amp;apos;t finish within the time-out 500">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.timeTestOne() didn't finish within the time-out 500
]]>
    </failure>
  </testcase> <!-- timeTestOne -->
</testsuite> <!-- Command line test -->
